name: snypix_flutter
description: "Snypix App with Flutter 3"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^5.0.0-release-candidate-5
  flutter_secure_storage:
  flutter_typeahead:
  pull_to_refresh_flutter3:
  google_maps_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  assets:
   - assets/images/login_bg.jpg
   - assets/images/logo_login.png

flutter_icons:
  image_path: assets/images/logo_launcher.png"
  android: launcher_icon
